package com.moviex.ai.model;

public enum AiIntent {
    MOVIE_RECOMMENDATION,
    SHOWTIME_LOOKUP,
    SEAT_RECOMMENDATION,
    UPCOMING_TICKETS,
    PREMIUM_BENEFITS,
    PAYMENT_FAILURE,
    BOOKING_HELP,
    SUBSCRIPTION_SUPPORT,
    PLATFORM_HELP,
    OFF_SCOPE
}
