# Server Configuration
server.port=8080

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/moviex
spring.data.mongodb.database=moviex

# Security Auto Config is now handled manually
# spring.autoconfigure.exclude=... (Removed)

# JWT Setup
moviex.app.jwtSecret=mySuperSecretKeyThatNeedsToBeLongEnoughForHS256ToWorkWhichMeansAtLeast256BitsOr32Characters
moviex.app.jwtExpirationMs=86400000
spring.devtools.livereload.enabled=false

# Mail config - Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=diepthong778@gmail.com
spring.mail.password=ptrl hsar sjve qimv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
